CREATE TABLE "card_applications" (
	"id" serial PRIMARY KEY NOT NULL,
	"merchant_external_id" text,
	"company_name" text NOT NULL,
	"company_rut" text NOT NULL,
	"company_address" text NOT NULL,
	"company_website_url" text,
	"contact_email" text NOT NULL,
	"legal_rep_name" text NOT NULL,
	"legal_rep_rut" text NOT NULL,
	"legal_rep_birth_date" text NOT NULL,
	"months_with_us" integer NOT NULL,
	"mcc" text,
	"regcheck_status" text NOT NULL,
	"regcheck_risk_level" text,
	"regcheck_tax_start_date" text,
	"regcheck_profile_url" text,
	"decision" text NOT NULL,
	"decision_reason" text NOT NULL,
	"customer_message" text NOT NULL,
	"raw_input" jsonb NOT NULL,
	"raw_regcheck" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL
);
