import * as z from 'zod';

const envSchema = z.object({
  DATABASE_URL: z.string().optional().default('postgresql://postgres:postgres@localhost:5432/postgres'),
  BETTER_AUTH_URL: z.string().optional().default('http://localhost:3001'),
  BETTER_AUTH_SECRET: z.string().min(32),
  KUSHKI_PRIVATE_API_KEY: z.string().optional(),
  KUSHKI_PUBLIC_MERCHANT_ID: z.string().optional(),
  KUSHKI_ENVIRONMENT: z.enum(['sandbox', 'production']).optional().default('sandbox'),
  REGCHECK_API_KEY: z.string().optional(),
  REGCHECK_BASE_URL: z.string().url().optional(),
  REGCHECK_CHECK_PATH: z.string().optional().default('/record/{API_KEY}'),
  REGCHECK_WEB_LOGIN_URL: z.string().url().optional().default('https://app.regcheq.com/login'),
  REGCHECK_WEB_USER: z.string().optional(),
  REGCHECK_WEB_PASSWORD: z.string().optional(),
  REGCHECK_WEB_HEADLESS: z.string().optional().default('true'),
  REGCHECK_WEB_STORAGE_STATE_PATH: z.string().optional().default('.cache/regcheck-storage-state.json'),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().optional().default('gpt-4o-mini'),
  SUPABASE_URL: z.string().url().optional(),
  SUPABASE_ANON_KEY: z.string().optional(),
  SUPABASE_SERVICE_ROLE_KEY: z.string().optional(),
  SUPABASE_MCC_COSTS_TABLE: z.string().optional().default('costos_mcc'),
  SUPABASE_MCC_ANNEXED_TABLE: z.string().optional().default('mcc_anexados_firmados'),
  SUPABASE_MCC_COLUMN: z.string().optional().default('mcc'),
  SUPABASE_MCC_COST_COLUMNS: z.string().optional().default('costo_credito,costo_debito,costo_prepago'),
  EMAIL_PROVIDER: z.string().optional(),
  EMAIL_API_KEY: z.string().optional(),
  EMAIL_FROM: z.string().email().optional().default('success@fintoc.com'),
  SLACK_BOT_TOKEN: z.string().optional(),
  SLACK_SIGNING_SECRET: z.string().optional(),
  SLACK_ALERTS_CHANNEL: z.string().optional(),
  SLACK_RAI_USER_ID: z.string().optional(),
  SLACK_ANTONIA_USER_ID: z.string().optional(),
  SLACK_ADDITIONAL_APPROVER_USER_IDS: z.string().optional(),
});

export const env = envSchema.parse(process.env);
